### ISSUE TITLE
[Solved] Check if MatrixSync installed, instead of providing multiple versions

### ISSUE THREAD

**Issue by alex3236** [Mooling0602/IPLocation-MCDR#1]
Do something like this:
```python3
psi = ServerInterface.psi()
send = psi.broadcast

try:
    from matrix_sync.reporter import sendMsg
    send = lambda *args, **kwargs: asyncio.run(sendMsg(*args, **kwargs))
except ModuleNotFoundError:
    logger.log('MatrixSync not found. Using server broadcast')

send('My IP Location is: Mars')
```
Instead of this:
![](https://github.com/user-attachments/assets/79078c30-ae34-4bfb-9337-75024b71907c)
when user install your plugin in MCDR, the "latest" release will be the msync one.

**Comment by Mooling0602** [comment]
将通过后续版本更新完成，感谢你的建议。

**Comment by Mooling0602** [comment]
> Do something like this:
> 
> ```python
> psi = ServerInterface.psi()
> send = psi.broadcast
> 
> try:
>     from matrix_sync.reporter import sendMsg
>     send = lambda *args, **kwargs: asyncio.run(sendMsg(*args, **kwargs))
> except ModuleNotFoundError:
>     logger.log('MatrixSync not found. Using server broadcast')
> 
> send('My IP Location is: Mars')
> ```
> 
> Instead of this: ![](https://private-user-images.githubusercontent.com/45303195/372323812-79078c30-ae34-4bfb-9337-75024b71907c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODQzNDgsIm5iZiI6MTczMDc4NDA0OCwicGF0aCI6Ii80NTMwMzE5NS8zNzIzMjM4MTItNzkwNzhjMzAtYWUzNC00YmZiLTkzMzctNzUwMjRiNzE5MDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA1MjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTM3ZTUwNTllMDYyNTIzZGY5ZTM0OGIyMjQxZTM1MWJjMTlmNjYyMTBkMDMyODI3OTVkNzBiZTUxODVlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lPHXXS7Rshz_Pipet4m5knk_8NTBVrjPdJVbUxvw30A) when user install your plugin in MCDR, the "latest" release will be the msync one.

警告：未定义“logger” - Pylance(reportUndefinedVariable)

**Comment by Mooling0602** [comment]
File "plugins/plugin.mcdr/iploc/__init__.py", line 13, in <module>
    logger.log('MatrixSync not found. Using server broadcast')
    ^^^^^^
NameError: name 'logger' is not defined

**Comment by Mooling0602** [comment]
已经发布相关更新，该问题彻底解决。
