### ISSUE TITLE
[已解决] 正常按照流程安装MCDR后，控制台报错无法运行

### ISSUE THREAD

**Issue by HeTao-yz** [Mooling0602/IPLocation-MCDR#2]
服务端为MCDR套Fabirc端。
![捕获](https://github.com/user-attachments/assets/c71b5000-f0ca-4d40-bf46-6b6a543f0a6a)
报错如上图

**Comment by Mooling0602** [comment]
抱歉源代码管理出现混乱，已重新上传确认无误的插件到Release，可以在GitHub下载，插件仓库将需要最多几个小时的时间进行刷新。

**Comment by Mooling0602** [comment]
请尝试最新版本v0.0.2，该问题已彻底解决。

**Comment by HeTao-yz** [comment]
感谢，已经可以正常使用！
